---
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.6
      hooks:
          - id: ruff
          - id: ruff-format
    # - repo: https://github.com/pre-commit/mirrors-mypy
    #   rev: v1.11.2
    #   hooks:
    #       - id: mypy
    #         args: [--ignore-missing-imports, --strict]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-toml
          - id: check-yaml
          - id: pretty-format-json
            args: [--autofix]
          - id: end-of-file-fixer
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
            exclude: openapi.yaml
            args: [--width, '110'] # Note this is < than the 120 in yamllint, but 120 seems to get longer lines than that...
