---
services:
    app: &app
        build:
            context: .
            target: dev
        depends_on: &depends
            postgres:
                condition: service_healthy
                restart: true
        volumes:
            - ./src:/home/src
            - ./tests:/home/tests
            - ./migrations:/home/migrations
        env_file: .env
        environment:
            POSTGRES_HOST: postgres
        command: bash -c "alembic upgrade head && uvicorn src.web.app:app --host 0.0.0.0 --port 8080 --reload"
        ports:
            - 8080:8080
        tty: true
    postgres:
        image: postgres:16
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - apartments_db:/var/lib/postgres/data
        healthcheck:
            test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
            interval: 10s
            start_period: 40s
            start_interval: 3s
            retries: 10
    nginx:
        image: nginx
        ports:
            - 8089:80
        volumes:
            - $PWD/http/nginx.conf:/etc/nginx/nginx.conf
            - ./http/www:/www
    # keeps failing
    # healthcheck:
    #   test: curl --fail http://localhost || exit 1
    #   interval: 60s
    #   start_interval: 3s
    #   start_period: 20s
    #   retries: 1
    test:
        <<: *app
        depends_on:
            nginx:
                condition: service_started
            <<: *depends
        command: bash -c "alembic upgrade head && coverage run -m pytest -vv -s"

volumes:
    apartments_db:
