---
services:
    app:
        build:
            context: .
            target: dev
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
        volumes:
            - ./src:/home/src
        env_file: .env
        environment:
            POSTGRES_HOST: postgres
        command: uvicorn src.web.app:app --host 0.0.0.0 --port 8080 --reload
        ports:
            - 8080:8080
    postgres:
        image: postgres:16
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - apartments_db:/var/lib/postgres/data
        healthcheck:
            test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
            interval: 10s
            start_period: 40s
            start_interval: 3s
            retries: 10
    nginx:
        image: nginx
        ports:
            - 8089:80
        volumes:
            - $PWD/http/nginx.conf:/etc/nginx/nginx.conf
            - ./http/www:/www

volumes:
    apartments_db:
