---
services:
    postgres:
        image: postgres:16
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - apartments_db:/var/lib/postgres/data
    nginx:
        image: nginx
        ports:
            - 8089:80
        volumes:
            - $PWD/static/nginx.conf:/etc/nginx/nginx.conf
            - ./http/www:/www


volumes:
    apartments_db:
