"""Bare essentials

Revision ID: 9269e33ed1b9
Revises: 57fecdf95897
Create Date: 2024-09-26 10:37:55.464583

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9269e33ed1b9"
down_revision: Union[str, None] = "57fecdf95897"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendarfile")
    op.drop_constraint("apartment_user_id_number_key", "apartment", type_="unique")
    op.drop_column("apartment", "created_at")
    op.add_column(
        "booking",
        sa.Column("guest_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booking", "guest_name")
    op.add_column(
        "apartment",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_unique_constraint(
        "apartment_user_id_number_key", "apartment", ["user_id", "number"]
    )
    op.create_table(
        "calendarfile",
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "source",
            postgresql.ENUM("DISK", "URL", name="filesource"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("sha", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("url", name="calendarfile_pkey"),
    )
    # ### end Alembic commands ###
