"""init

Revision ID: f2bf984ca682
Revises:
Create Date: 2024-09-29 22:14:04.246429

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f2bf984ca682"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "apartment",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "booking",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("cleaning_deadline", sa.Date(), nullable=True),
        sa.Column("cleaning_date", sa.Date(), nullable=False),
        sa.Column("guest_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("apartment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.CheckConstraint("cleaning_date >= end_date"),
        sa.CheckConstraint("cleaning_deadline >= cleaning_date"),
        sa.ForeignKeyConstraint(
            ["apartment_id"],
            ["apartment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "booking_start_date_end_date_idx",
        "booking",
        ["start_date", "end_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("booking_start_date_end_date_idx", table_name="booking")
    op.drop_table("booking")
    op.drop_table("apartment")
    op.drop_table("user")
    # ### end Alembic commands ###
